### PR TITLE
removed itextsharp and added PdfBox

### PR DESCRIPTION
**Pull request by EnterpriseWide**
Hey there!
iTextSharp is expensive for small projects.
So in this pull request I have added PdfBox and removed iTextSharp.
I hope that is helpful. Please let me know if there is a better way forward and I will see if I can do that for you instead.

### CODE REVIEW

**Comment by EnterpriseWide** [comment]
You should be able to remove all the licencing concerns with this I hope due to no AGPL being involved now.

**Comment by Shazwazza** [comment]
Fantastic work. I realize iTextSharp licensing is annoying. The only issue I see with this is the dependency on java vm's which will could be mighty slow. I think a little bit of benchmarking should be done to see what the actually difference is. We could also look at making the PDF reading part abstracted so we can easily release different versions that can use a different underlying PDF engine. I will review further when time permits.

**Comment by EnterpriseWide** [comment]
Yeah cool on the “when time permits thing”!

Work Life Balance being in focus at the moment makes it even harder I suppose :)
I would rather you spend your time on putting an angular app with token authentication and authenticated hal together anyway and getting rid of all those dlls. Looking forward to a few things that you guys are working on.

Anyway, back to the PDF Indexer though, I thought that building the index quickly probably isn’t as important as searching the index so I figured it would be a good compromise with removing the licence.

Its just cash really that clinches it for me. I got a quote for around 2. K USD which is crazy hard to sell to the client.

Anyway, I have built the PdfBox version and am using it in my latest. It’s working fine.

Let me know if you need anything further and thanks for the library. #h5yr #respect

Regards

**Comment by Shazwazza** [comment]
We've released v2.0.0 for umbraco 8 which uses PDFSharp which is MIT licensed. The implementation is now replaceable so you would easily be able to replace it with PdfBox if you chose to.

**Pull request closed without merging**
